
export *from"./CardDetail/CardDetail"
export *from"./Footer/Footer"
export *from"./Header/Header"
export *from"./Main/Main"
export *from"./Navbar/Navbar"
export *from"./CartaDentro/CartaDentro"
export *from"./PokemonInfo/PokemonInfo"
export *from"./BotonAtras/BotonAtras"
export *from"./BotonTipo/BotonTipo"