export *from"./Card/Card"
export *from"./CardDistrito/CardDistrito"
export *from"./Header/Header"
export *from"./Footer/Footer"
export *from"./UploadFile/Uploadfile"
export *from"./CardTitan/CardTitan"
